"""Built-in operational defaults.

These values are deliberately kept in code rather than exposed as required
environment variables. Deployment-specific values (credentials, endpoints,
databases and origins) remain configurable through ``.env``.
"""

DEFAULT_WORKSPACE_ROOT = "data/workspaces"
DEFAULT_CONVERSATION_HISTORY_ROOT = "data/conversations"
DEFAULT_WORKSPACE_ALLOWED_ROOTS = ""
DEFAULT_ARTIFACTS_ROOT = "data/artifacts"
DEFAULT_MODEL_CONCURRENCY = 4
DEFAULT_MODEL_TIMEOUT_SECONDS = 300.0
PROVIDER_REQUEST_TIMEOUT_SECONDS = 300.0
DEFAULT_CONTEXT_COMPRESSION_THRESHOLD = 0.85
DEFAULT_CONTEXT_COMPRESSION_TARGET = 0.60
DEFAULT_CONTEXT_SAFETY_MARGIN_RATIO = 0.02
DEFAULT_CONTEXT_UNKNOWN_MODEL_WINDOW = 128_000
DEFAULT_CONTEXT_UNKNOWN_MODEL_MAX_OUTPUT_TOKENS = 8_192
DEFAULT_CONTEXT_MODEL_WINDOWS = ""
DEFAULT_CONTEXT_MODEL_MAX_OUTPUT_TOKENS = ""
DEFAULT_CONTEXT_RECENT_MESSAGES = 12
DEFAULT_MEMORY_ENABLED = False
DEFAULT_MEMORY_HARD_ENABLED = True
DEFAULT_MEMORY_ENVIRONMENT_ENABLED = True
DEFAULT_MEMORY_EPISODIC_ENABLED = True
DEFAULT_MEMORY_AUTO_CONSOLIDATION_ENABLED = False
DEFAULT_MEMORY_DEFAULT_OWNER_ID = "local-user"
DEFAULT_MEMORY_MAX_CONTEXT_ITEMS = 5
DEFAULT_MEMORY_MAX_CONTEXT_TOKENS = 8_000
DEFAULT_MEMORY_MIN_RETRIEVAL_SCORE = 0.35
DEFAULT_MEMORY_CONSOLIDATION_MAX_ATTEMPTS = 3
DEFAULT_MEMORY_RETENTION_DAYS = 365
DEFAULT_MEMORY_ENVIRONMENT_MAX_FILE_BYTES = 262_144
DEFAULT_TOOL_TIMEOUT_SECONDS = 120.0
DEFAULT_MENTION_EXECUTION_TOOLS = (
    "list_workspace_files,read_workspace_file,search_workspace_files,create_workspace_file,"
    "modify_workspace_file,run_allowlisted_check"
)
DEFAULT_SKILLS_ROOT = "skills"
DEFAULT_MCP_CONFIG_PATH = "config/mcp_servers.yaml"
DEFAULT_MCP_CONNECT_TIMEOUT_SECONDS = 300.0
DEFAULT_MCP_READ_TOOL_TIMEOUT_SECONDS = 30.0
DEFAULT_MCP_TOOL_TIMEOUT_SECONDS = 300.0
DEFAULT_MCP_CLOSE_TIMEOUT_SECONDS = 0.5
DEFAULT_CORS_ORIGINS = "http://localhost:5173,http://127.0.0.1:5173"
DEFAULT_SSE_POLL_INTERVAL_SECONDS = 0.1
DEFAULT_SSE_HEARTBEAT_SECONDS = 15.0
DEFAULT_LOG_LEVEL = "INFO"
